[platformio]
core_dir = .platformio

[env]
framework = arduino
monitor_speed = 115200

[env:lolin_d32_pro]
platform = platformio/espressif32 @ 7.0.1
board = lolin_d32_pro

[env:nodemcu]
platform = platformio/espressif8266 @ 2.6.3
board = nodemcu
